sudo: required
services:
  - docker
before_install:
  - docker build -t andreadaru/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andreadaru/docker-react npm run test -- --coverage